### ISSUE TITLE
teacher or student model are not find？please give me where，thanks

### ISSUE THREAD

**Issue by huozhong12** [ZinuoLi/hwen#2]

**Comment by xuhangc** [comment]
Hi, [this](https://github.com/leiyingtie/UWFormer/blob/dde9c688903eb076bf47ff5e6eec4a8c05163e4d/models/UW_Enhance.py#L53) is the teacher and student model, we apply the same semi-supervised method like [Semi-UIR](https://github.com/Huang-ShiRui/Semi-UIR).
